### ISSUE TITLE
Pictures Filter

### ISSUE THREAD

**Issue by ThomasRavail** [tomolimo/ticketcleaner#9]
I tried to filter the pictures we received via the GLPI mail collector. So, I sent a first mail with Outlook with my signature containing our logos and I put the pictures in the 'pictures' folder of the plugin. I tried a second time to send an email and the ticket did not contain any logo.

But if another person try to send an email containing the same signature with same logos, in TicketCleaner.log, we can see different hash even if pictures are same.

Could you help me to resolve this issue ?

Thank you in advance

**Comment by tomolimo** [comment]
Hello @ThomasRavail 
Sorry for being late to answer.
The issue is related to Outlook that re-samples the pictures that are in email body, and when an image is re-sampled, of course the hash codes don't match.
The only solution I found is to save all pictures that passed the ticketCleaner filter each time you have some.
Thank you
Regards,
Tomolimo
